### Site Settings ###
title               : Seb Duerr
description         : >-
                      :blue_heart: Joy in my life.
baseurl             : ""                               
repository          : seduerr91/seduerr91              
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blogideas.md
  - pages/hidden-2024.md
  - pages/hidden-investing.md
  - pages/castle-investment-banking.md
  - pages/castle-leadership-motivation.md
  - pages/castle-mental-castles.md
  - pages/castle-algorithms-and-data-structures.md
  - pages/castle-beautiful-questions.md
  - pages/castle-cloud-infrastructure.md
  - pages/castle-object-oriented-python.md
  - pages/castle-deep-learning.md
  - pages/castle-funny-stories.md
  - pages/castle-machine-learning.md
  - pages/castle-philosophy.md
  - pages/castle-software-philosophy.md
  - pages/castle-regex.md
  - pages/castle-clean-code.md
  - pages/castle-golang.md
  - pages/castle-difference.md
  - pages/castle-think-again.md
  - pages/castle-architectural-principles.md
  - pages/castle-personal-mba.md
  - pages/castle-business.md
  - pages/castles.md
  - pages/schedule.md

### Author Info ###
author:
  name              : Seb Duerr
  image             : https://i.imgur.com/r0yP47Um.png
#  behance           : your_username
# dribbble          : your_username
  email             : duerr.sebastian@gmail.com
  facebook          : seduerr
  github            : seduerr91
  gitlab            : seduerr
  kaggle            : sebastian91
  linkedin          : sebastianduerr
  medium            : duerr.sebastian
# soundcloud        : your_username
# spotify           : 
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : duerrseb
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Disqus ###
disqus: duerr                          # Your website Shortname on disqus


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
